version: '3'
services:
    app:
        image: 'mattermost/focalboard'
        container_name: focalboard
        restart: 'always'
        ports:
            - '3011:8000'
        volumes:
            - '/mnt/raid5/focalboard/data:/data'
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
